## Database Properties
spring.datasource.url=jdbc:mysql:///users-db?cloudSqlInstance=project-817c78ce-3593-452e-953:us-central1:usersdblab&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=${db.user}&password{db.pw}&useSSL=FALSE

db.project = ${POSTGRES_DB_USER}
db.project = ${POSTGRES_DB_PASS}

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

